id: P009452
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN3430
  title: བླ་རུང་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    d90934ff895348cab483b4ceccac1951:
      image_group_id: I3CN4017
      title: ''
      volume_number: 1
      total_pages: 374
      base_file: v001.txt
